In [1]:
import numpy as np

# Create the array
arr = np.arange(6)

# Print the array
print("Array:", arr)

# Print the data type
print("Data type:", arr.dtype)


Array: [0 1 2 3 4 5]
Data type: int64


In [4]:
import numpy as np

# Given array
arr = np.array([1.5, 2.6, 3.7])

# Check if the data type is float64
if arr.dtype == np.float64:
    print("The data type of the array is float64.")
else:
    print("The data type of the array is not float64.")


The data type of the array is float64.


Explanation:

    arr.dtype retrieves the data type of the array.
    np.float64 is the NumPy data type for 64-bit floating-point numbers.
    The if statement checks whether the data type of arr is float64.

When you run this code with the given array arr = np.array([1.5, 2.6, 3.7]), it will print:

In [5]:
import numpy as np

# Create the array with complex128 data type
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)

# Print the array
print("Array:", arr)

# Print the data type of the array
print("Data type:", arr.dtype)


Array: [1.+2.j 3.+4.j 5.+6.j]
Data type: complex128


Explanation:

    The np.array() function creates the array with the specified complex numbers.
    The dtype=np.complex128 argument ensures that the array has the complex128 data type, which is a 128-bit complex number.

In [6]:
import numpy as np

# Example integer array
arr = np.array([1, 2, 3, 4, 5])

# Convert the array to float32 data type
arr_float32 = arr.astype(np.float32)

# Print the original and converted arrays
print("Original array:", arr)
print("Original data type:", arr.dtype)
print("Converted array:", arr_float32)
print("Converted data type:", arr_float32.dtype)


Original array: [1 2 3 4 5]
Original data type: int64
Converted array: [1. 2. 3. 4. 5.]
Converted data type: float32


Explanation:

    The astype(np.float32) method converts the data type of the array to float32.
    The original array remains unchanged, and a new array with the float32 data type is created.

In [7]:
import numpy as np

# Example array with float64 data type
arr = np.array([1.23456789, 2.34567891, 3.45678912], dtype=np.float64)

# Convert the array to float32 data type
arr_float32 = arr.astype(np.float32)

# Print the original and converted arrays
print("Original array:", arr)
print("Original data type:", arr.dtype)
print("Converted array:", arr_float32)
print("Converted data type:", arr_float32.dtype)


Original array: [1.23456789 2.34567891 3.45678912]
Original data type: float64
Converted array: [1.2345679 2.3456788 3.456789 ]
Converted data type: float32


Explanation:

    The astype(np.float32) method converts the array from float64 (64-bit floating point) to float32 (32-bit floating point), reducing the decimal precision.
    The original array remains unchanged, and a new array with the float32 data type is created.

In [8]:
import numpy as np

def array_attributes(arr):
    shape = arr.shape    # Get the shape of the array
    size = arr.size      # Get the size (number of elements) of the array
    dtype = arr.dtype    # Get the data type of the array

    return shape, size, dtype

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(arr)

print("Shape:", shape)
print("Size:", size)
print("Data type:", dtype)


Shape: (2, 3)
Size: 6
Data type: int64


Explanation:

    arr.shape: Returns the shape of the array, which is a tuple representing the dimensions of the array.
    arr.size: Returns the total number of elements in the array.
    arr.dtype: Returns the data type of the elements in the array.

In [9]:
import numpy as np

def array_dimension(arr):
    # Return the number of dimensions of the array
    return arr.ndim

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
dimensionality = array_dimension(arr)

print("Dimensionality:", dimensionality)


Dimensionality: 2


Explanation:

    arr.ndim: Returns the number of dimensions (or axes) of the array.

In [10]:
import numpy as np

def item_size_info(arr):
    item_size = arr.itemsize    # Size of each element in bytes
    total_size = arr.nbytes      # Total size of the array in bytes
    
    return item_size, total_size

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
item_size, total_size = item_size_info(arr)

print("Item size:", item_size, "bytes")
print("Total size:", total_size, "bytes")


Item size: 8 bytes
Total size: 48 bytes


Explanation:

    arr.itemsize: Returns the size (in bytes) of each element in the array.
    arr.nbytes: Returns the total number of bytes consumed by the elements of the array.

In [11]:
import numpy as np

def array_strides(arr):
    # Return the strides of the array
    return arr.strides

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)

print("Strides:", strides)


Strides: (24, 8)


Explanation:

    arr.strides: Returns the strides of the array as a tuple. Each value in the tuple represents the number of bytes to step in each dimension when traversing the array.

In [12]:
import numpy as np

def shape_stride_relationship(arr):
    shape = arr.shape    # Get the shape of the array
    strides = arr.strides # Get the strides of the array
    
    return shape, strides

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(arr)

print("Shape:", shape)
print("Strides:", strides)


Shape: (2, 3)
Strides: (24, 8)


In [13]:
import numpy as np

def create_zeros_array(n):
    # Create an array of zeros with n elements
    return np.zeros(n)

# Example usage:
n = 5
zeros_array = create_zeros_array(n)

print("Array of zeros:", zeros_array)


Array of zeros: [0. 0. 0. 0. 0.]


Explanation:

    np.zeros(n): Creates a NumPy array of shape (n,) filled with zeros. The array has n elements, all initialized to zero.

In [14]:
import numpy as np

def create_ones_matrix(rows, cols):
    # Create a 2D array of ones with dimensions rows x cols
    return np.ones((rows, cols))

# Example usage:
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)

print("2D array of ones:\n", ones_matrix)


2D array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Explanation:

    np.ones((rows, cols)): Creates a 2D NumPy array with the specified number of rows and columns, filled with ones. The shape of the array is (rows, cols).

In [15]:
import numpy as np

def generate_range_array(start, stop, step):
    # Create a NumPy array with the specified range and step
    return np.arange(start, stop, step)

# Example usage:
start = 0
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)

print("Range array:", range_array)


Range array: [0 2 4 6 8]


Explanation:

    np.arange(start, stop, step): Creates a NumPy array with values starting from start, ending before stop, and with increments of step.

In [16]:
import numpy as np

def generate_linear_space(start, stop, num):
    # Create a NumPy array with num equally spaced values between start and stop (inclusive)
    return np.linspace(start, stop, num)

# Example usage:
start = 0.0
stop = 1.0
num = 5
linear_space_array = generate_linear_space(start, stop, num)

print("Linear space array:", linear_space_array)


Linear space array: [0.   0.25 0.5  0.75 1.  ]


Explanation:

    np.linspace(start, stop, num): Generates num equally spaced values between start and stop (inclusive). The function ensures that both start and stop are included in the output array.

In [17]:
import numpy as np

def create_identity_matrix(n):
    # Create a square identity matrix of size n x n
    return np.eye(n)

# Example usage:
n = 4
identity_matrix = create_identity_matrix(n)

print("Identity matrix:\n", identity_matrix)


Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Explanation:

    np.eye(n): Generates an n x n identity matrix. An identity matrix has ones on the diagonal and zeros elsewhere.

In [18]:
import numpy as np

def list_to_array(py_list):
    # Convert the Python list to a NumPy array
    return np.array(py_list)

# Example usage:
py_list = [1, 2, 3, 4, 5]
numpy_array = list_to_array(py_list)

print("NumPy array:", numpy_array)


NumPy array: [1 2 3 4 5]


Explanation:

    np.array(py_list): Converts the Python list py_list into a NumPy array.

In [19]:
import numpy as np

# Create a NumPy array
original_array = np.array([1, 2, 3, 4, 5], dtype=np.int32)

# Create a view of the original array with the same data but with a different data type
array_view = original_array.view(dtype=np.float32)

# Print the original array and the view
print("Original array:", original_array)
print("Original array data type:", original_array.dtype)

print("Array view:", array_view)
print("Array view data type:", array_view.dtype)


Original array: [1 2 3 4 5]
Original array data type: int32
Array view: [1.e-45 3.e-45 4.e-45 6.e-45 7.e-45]
Array view data type: float32


Explanation:

    original_array.view(dtype=np.float32): Creates a new view of the original array with a different data type (float32 in this case). The underlying data is shared, so modifying the data in the view will affect the original array and vice versa.
    dtype: Specifies the data type of the view.

In [20]:
import numpy as np

def concatenate_arrays(array1, array2, axis):
    # Concatenate the two arrays along the specified axis
    return np.concatenate((array1, array2), axis=axis)

# Example usage:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Concatenate along axis 0 (rows)
concatenated_axis0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:\n", concatenated_axis0)

# Concatenate along axis 1 (columns)
concatenated_axis1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 1:\n", concatenated_axis1)


Concatenated along axis 0:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Concatenated along axis 1:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Explanation:

    np.concatenate((array1, array2), axis=axis): Concatenates the two input arrays along the specified axis.
        axis=0 concatenates along the rows (vertical stacking).
        axis=1 concatenates along the columns (horizontal stacking).

In [21]:
import numpy as np

# Create two NumPy arrays with the same number of rows but different numbers of columns
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8], [9, 10]])

# Concatenate the arrays horizontally (along axis 1)
concatenated_array = np.concatenate((array1, array2), axis=1)

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Concatenated array:\n", concatenated_array)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8]
 [ 9 10]]
Concatenated array:
 [[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


Explanation:

    np.concatenate((array1, array2), axis=1): Concatenates array1 and array2 along the columns (axis 1). The arrays must have the same number of rows for this to work.

In [22]:
import numpy as np

def vertical_stack(arrays):
    # Vertically stack multiple NumPy arrays given as a list
    return np.vstack(arrays)

# Example usage:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
array3 = np.array([[13, 14, 15]])

# List of arrays to stack
arrays_list = [array1, array2, array3]

# Stack the arrays vertically
stacked_array = vertical_stack(arrays_list)

print("Stacked array:\n", stacked_array)


Stacked array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


Explanation:

    np.vstack(arrays): Stacks the arrays vertically (along axis 0). All arrays must have the same number of columns.

In [23]:
import numpy as np

def create_range_array(start, stop, step):
    """
    Create a NumPy array of integers within the specified range [start, stop] (inclusive) with the given step size.
    
    Parameters:
    start (int): The start of the range (inclusive).
    stop (int): The end of the range (inclusive).
    step (int): The step size between each number in the range.
    
    Returns:
    np.ndarray: Array of integers within the specified range with the given step size.
    """
    # Create an array of integers from start to stop (inclusive) with the specified step size
    return np.arange(start, stop + 1, step)

# Example usage:
start = 1
stop = 10
step = 2

range_array = create_range_array(start, stop, step)

print("Range array:", range_array)


Range array: [1 3 5 7 9]


Explanation:

    np.arange(start, stop + 1, step): Generates an array of integers starting from start and ending at stop (inclusive), with a specified step. Adding 1 to stop ensures that the stop value is included if it fits within the specified step size.

In [24]:
import numpy as np

def generate_equally_spaced_array(start, stop, num):
    """
    Generate a NumPy array of `num` equally spaced values between `start` and `stop` (inclusive).
    
    Parameters:
    start (float): The start of the range (inclusive).
    stop (float): The end of the range (inclusive).
    num (int): The number of equally spaced values to generate.
    
    Returns:
    np.ndarray: Array of equally spaced values.
    """
    # Generate an array of `num` equally spaced values between `start` and `stop` (inclusive)
    return np.linspace(start, stop, num)

# Example usage:
start = 0
stop = 1
num = 10

array = generate_equally_spaced_array(start, stop, num)

print("Array of equally spaced values:", array)


Array of equally spaced values: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Explanation:

    np.linspace(start, stop, num): Generates num equally spaced values between start and stop, including both endpoints.

In [25]:
import numpy as np

def generate_log_space_array(start, stop, num):
    """
    Generate a NumPy array of `num` logarithmically spaced values between `start` and `stop` (inclusive).
    
    Parameters:
    start (float): The start of the range (base 10 logarithm of the smallest value).
    stop (float): The end of the range (base 10 logarithm of the largest value).
    num (int): The number of logarithmically spaced values to generate.
    
    Returns:
    np.ndarray: Array of logarithmically spaced values.
    """
    # Generate an array of `num` logarithmically spaced values between `10**start` and `10**stop`
    return np.logspace(start, stop, num)

# Example usage:
start = 0  # log10(1)
stop = 3   # log10(1000)
num = 5

log_space_array = generate_log_space_array(start, stop, num)

print("Logarithmically spaced values:", log_space_array)


Logarithmically spaced values: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


Explanation:

    np.logspace(start, stop, num): Generates num logarithmically spaced values between 10start10start and 10stop10stop. The values are spaced evenly on a logarithmic scale.

In [26]:
import numpy as np
import pandas as pd

# Generate a NumPy array with random integers between 1 and 100
np_array = np.random.randint(1, 101, size=(5, 3))

# Create a Pandas DataFrame from the NumPy array
df = pd.DataFrame(np_array, columns=['Column1', 'Column2', 'Column3'])

# Print the DataFrame
print(df)


   Column1  Column2  Column3
0       64       76       79
1       41       56       51
2       60       75       61
3       34        5       42
4       45       88       30


Explanation:

    np.random.randint(1, 101, size=(5, 3)): Generates a NumPy array of shape (5, 3) with random integers between 1 (inclusive) and 100 (exclusive).
    pd.DataFrame(np_array, columns=['Column1', 'Column2', 'Column3']): Creates a Pandas DataFrame from the NumPy array. You can specify column names using the columns parameter.

In [27]:
import pandas as pd
import numpy as np

def replace_negatives_with_zeros(df, column_name):
    """
    Replace all negative values in a specific column of the DataFrame with zeros.
    
    Parameters:
    df (pd.DataFrame): The DataFrame containing the data.
    column_name (str): The name of the column in which to replace negative values.
    
    Returns:
    pd.DataFrame: DataFrame with negative values replaced by zeros in the specified column.
    """
    # Use NumPy operations to replace negative values with zeros in the specified column
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

# Example usage:
# Create a sample DataFrame
data = {'A': [10, -5, 3, -1], 'B': [-2, 15, -7, 8]}
df = pd.DataFrame(data)

print("Original DataFrame:\n", df)

# Replace negative values in column 'A' with zeros
df_modified = replace_negatives_with_zeros(df, 'A')

print("Modified DataFrame:\n", df_modified)


Original DataFrame:
     A   B
0  10  -2
1  -5  15
2   3  -7
3  -1   8
Modified DataFrame:
     A   B
0  10  -2
1   0  15
2   3  -7
3   0   8


Explanation:

    np.where(condition, x, y): This function returns an array with elements chosen from x or y depending on the condition. Here, if the condition (df[column_name] < 0) is True, it replaces the value with 0; otherwise, it keeps the original value.
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name]): This line applies the np.where function to the specified column in the DataFrame, replacing negative values with zeros.

In [28]:
import numpy as np

# Given NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Access the 3rd element (index 2)
third_element = arr[2]

print("The 3rd element is:", third_element)


The 3rd element is: 30


Explanation:

    arr[2]: Accesses the element at index 2, which is the 3rd element in zero-indexed arrays.

In [29]:
import numpy as np

# Given 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Retrieve the element at index (1, 2)
element = arr_2d[1, 2]

print("Element at index (1, 2) is:", element)


Element at index (1, 2) is: 6


Explanation:

    arr_2d[1, 2]: Accesses the element in the 2nd row (index 1) and the 3rd column (index 2) of the 2D array.

In [30]:
import numpy as np

# Given NumPy array
arr = np.array([3, 8, 2, 10, 5, 7])

# Create a boolean mask for elements greater than 5
mask = arr > 5

# Extract elements using the boolean mask
filtered_elements = arr[mask]

print("Elements greater than 5 are:", filtered_elements)


Elements greater than 5 are: [ 8 10  7]


Explanation:

    arr > 5: Creates a boolean array where each position is True if the corresponding element in arr is greater than 5, and False otherwise.
    arr[mask]: Uses the boolean mask to filter and return only the elements of arr where the mask is True.

In [31]:
import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Extract elements from index 2 to 5 (inclusive)
sliced_elements = arr[2:6]

print("Elements from index 2 to 5 are:", sliced_elements)


Elements from index 2 to 5 are: [3 4 5 6]


Explanation:

    arr[2:6]: Slices the array starting from index 2 up to, but not including, index 6.

In [32]:
import numpy as np

# Given 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slice to extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[0:2, 1:3]

print("Extracted sub-array:\n", sub_array)


Extracted sub-array:
 [[2 3]
 [5 6]]


Explanation:

    arr_2d[0:2, 1:3]:
        0:2 specifies the rows from index 0 to 1 (excluding index 2).
        1:3 specifies the columns from index 1 to 2 (excluding index 3).

In [33]:
import numpy as np

def extract_elements_from_indices(arr_2d, indices):
    """
    Extract elements from a 2D NumPy array based on provided indices.

    Parameters:
    arr_2d (np.ndarray): The 2D NumPy array from which elements are to be extracted.
    indices (np.ndarray): A 2D array of indices where each row specifies the (row, column) index of the element to extract.

    Returns:
    np.ndarray: Array of extracted elements based on the provided indices.
    """
    # Convert indices to row and column indices
    row_indices, col_indices = indices[:, 0], indices[:, 1]

    # Use advanced indexing to extract elements
    extracted_elements = arr_2d[row_indices, col_indices]
    
    return extracted_elements

# Example usage:
# Given 2D NumPy array
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

# Array of indices where each row is a (row, column) pair
indices = np.array([[0, 1],  # Element at (0, 1) -> 20
                    [1, 2],  # Element at (1, 2) -> 60
                    [2, 0]]) # Element at (2, 0) -> 70

# Extract elements based on indices
extracted_elements = extract_elements_from_indices(arr_2d, indices)

print("Extracted elements:", extracted_elements)


Extracted elements: [20 60 70]


Explanation:

    indices[:, 0]: Extracts the row indices from the indices array.
    indices[:, 1]: Extracts the column indices from the indices array.
    arr_2d[row_indices, col_indices]: Uses advanced indexing to extract the elements specified by the row and column indices.

In [34]:
import numpy as np

def filter_elements_greater_than_threshold(arr, threshold):
    """
    Filter elements greater than a specified threshold from a 1D NumPy array.

    Parameters:
    arr (np.ndarray): The 1D NumPy array from which elements will be filtered.
    threshold (float): The threshold value to compare against.

    Returns:
    np.ndarray: Array of elements greater than the specified threshold.
    """
    # Create a boolean mask for elements greater than the threshold
    mask = arr > threshold

    # Use the mask to filter elements
    filtered_elements = arr[mask]
    
    return filtered_elements

# Example usage:
# Given 1D NumPy array
arr = np.array([1, 5, 8, 12, 3, 7])

# Define the threshold
threshold = 6

# Filter elements greater than the threshold
filtered_elements = filter_elements_greater_than_threshold(arr, threshold)

print("Elements greater than threshold:", filtered_elements)


Elements greater than threshold: [ 8 12  7]


Explanation:

    arr > threshold: Creates a boolean array where each position is True if the corresponding element in arr is greater than the threshold, and False otherwise.
    arr[mask]: Uses the boolean mask to filter and return only the elements where the mask is True.

In [35]:
import numpy as np

def extract_elements_from_3d_array(arr_3d, row_indices, col_indices, depth_indices):
    """
    Extract specific elements from a 3D NumPy array using indices provided for each dimension.

    Parameters:
    arr_3d (np.ndarray): The 3D NumPy array from which elements are to be extracted.
    row_indices (np.ndarray): Array of row indices.
    col_indices (np.ndarray): Array of column indices.
    depth_indices (np.ndarray): Array of depth indices.

    Returns:
    np.ndarray: Array of extracted elements based on the provided indices.
    """
    # Use advanced indexing to extract elements
    extracted_elements = arr_3d[row_indices, col_indices, depth_indices]
    
    return extracted_elements

# Example usage:
# Given 3D NumPy array
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],
                   
                   [[19, 20, 21],
    


SyntaxError: incomplete input (126152461.py, line 32)

Explanation:

    row_indices, col_indices, depth_indices: These arrays specify the indices in the first, second, and third dimensions of the 3D array, respectively.
    arr_3d[row_indices, col_indices, depth_indices]: Uses advanced indexing to extract elements from the 3D array based on the provided indices.

In [36]:
import numpy as np

def filter_elements_with_conditions(arr, condition1, condition2):
    """
    Return elements from an array where both conditions are satisfied using boolean indexing.

    Parameters:
    arr (np.ndarray): The NumPy array to filter.
    condition1 (np.ndarray): A boolean array representing the first condition.
    condition2 (np.ndarray): A boolean array representing the second condition.

    Returns:
    np.ndarray: Array of elements where both conditions are satisfied.
    """
    # Ensure both conditions are boolean arrays of the same shape
    if not (arr.shape == condition1.shape == condition2.shape):
        raise ValueError("Shape of conditions must match the shape of the array")
    
    # Combine the conditions using logical AND
    combined_condition = condition1 & condition2

    # Filter elements based on the combined condition
    filtered_elements = arr[combined_condition]
    
    return filtered_elements

# Example usage:
# Given NumPy array
arr = np.array([1, 5, 8, 12, 3, 7])

# Define two conditions
condition1 = arr > 4   # Condition: elements greater than 4
condition2 = arr < 10  # Condition: elements less than 10

# Get elements where both conditions are satisfied
filtered_elements = filter_elements_with_conditions(arr, condition1, condition2)

print("Elements satisfying both conditions:", filtered_elements)


Elements satisfying both conditions: [5 8 7]


Explanation:

    condition1 and condition2: Boolean arrays that represent the conditions to be satisfied.
    condition1 & condition2: Combines the two conditions using the logical AND operator. This results in a boolean array where an element is True if both conditions are True.
    arr[combined_condition]: Filters the original array to include only those elements where the combined condition is True.

In [37]:
import numpy as np

def extract_elements_from_2d_array(arr_2d, row_indices, col_indices):
    """
    Extract elements from a 2D NumPy array using row and column indices provided in separate arrays.

    Parameters:
    arr_2d (np.ndarray): The 2D NumPy array from which elements are to be extracted.
    row_indices (np.ndarray): Array of row indices.
    col_indices (np.ndarray): Array of column indices.

    Returns:
    np.ndarray: Array of extracted elements based on the provided indices.
    """
    # Ensure row_indices and col_indices have the same length
    if len(row_indices) != len(col_indices):
        raise ValueError("Length of row_indices and col_indices must be the same")

    # Use advanced indexing to extract elements
    extracted_elements = arr_2d[row_indices, col_indices]
    
    return extracted_elements

# Example usage:
# Given 2D NumPy array
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

# Arrays of row and column indices
row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 1, 0])

# Extract elements based on indices
extracted_elements = extract_elements_from_2d_array(arr_2d, row_indices, col_indices)

print("Extracted elements:", extracted_elements)


Extracted elements: [30 50 70]


Explanation:

    row_indices: Array specifying which rows to access.
    col_indices: Array specifying which columns to access.
    arr_2d[row_indices, col_indices]: Uses advanced indexing to extract elements from the 2D array based on the provided row and column indices.

In [38]:
import numpy as np

# Given NumPy array of shape (3, 3)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Scalar value to add
scalar_value = 5

# Add scalar value to each element of the array
result = arr + scalar_value

print("Original array:\n", arr)
print("Array after adding scalar value of 5:\n", result)


Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after adding scalar value of 5:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


Explanation:

    arr + scalar_value: This operation uses broadcasting to add the scalar value 5 to each element of the array. NumPy automatically applies the scalar addition to each element in the array.

In [39]:
import numpy as np

# Given arrays
arr1 = np.array([[2, 3, 4]])  # Shape (1, 3)
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])  # Shape (3, 4)

# Multiply each row of arr2 by the corresponding element in arr1
result = arr2 * arr1

print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Result of multiplication:\n", result)


ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

Explanation:

    arr2 * arr1: NumPy broadcasting automatically aligns the shapes of the two arrays. Since arr1 has shape (1, 3) and arr2 has shape (3, 4), broadcasting will stretch arr1 along the rows of arr2 to match the shape (3, 4). Each element of arr1 will be multiplied with the corresponding row of arr2.

In [40]:
import numpy as np

# Given arrays
arr1 = np.array([[1, 2, 3, 4]])  # Shape (1, 4)
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])  # Shape (4, 3)

# To add arr1 to each row of arr2, arr1 should be reshaped to match arr2's shape
# Reshape arr1 to (4, 4) by broadcasting
arr1_broadcasted = np.tile(arr1, (arr2.shape[0], 1))

# Add the reshaped arr1 to each row of arr2
result = arr2 + arr1_broadcasted[:, :arr2.shape[1]]

print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Result of addition:\n", result)


arr1:
 [[1 2 3 4]]
arr2:
 [[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
Result of addition:
 [[ 11  22  33]
 [ 41  52  63]
 [ 71  82  93]
 [101 112 123]]


Explanation:

    arr1_broadcasted: np.tile(arr1, (arr2.shape[0], 1)) replicates arr1 to match the number of rows in arr2. This reshaping allows element-wise addition with each row of arr2.
    arr1_broadcasted[:, :arr2.shape[1]]: Selects the first three columns of the broadcasted arr1 to match the shape of arr2.

In [41]:
import numpy as np

# Given arrays
arr1 = np.array([[1], [2], [3]])  # Shape (3, 1)
arr2 = np.array([[10, 20, 30]])    # Shape (1, 3)

# Add the arrays using broadcasting
result = arr1 + arr2

print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Result of addition:\n", result)


arr1:
 [[1]
 [2]
 [3]]
arr2:
 [[10 20 30]]
Result of addition:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


Explanation:

    arr1 has shape (3, 1), meaning it has 3 rows and 1 column.
    arr2 has shape (1, 3), meaning it has 1 row and 3 columns.
    When you add arr1 and arr2, NumPy broadcasts arr1 across the columns and arr2 across the rows to produce a result with shape (3, 3).

In [42]:
import numpy as np

# Given arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])  # Shape (2, 3)

arr2 = np.array([[10, 20],
                 [30, 40]])  # Shape (2, 2)

# Adjust arr2 to have the same shape as arr1
# This involves broadcasting arr2 to match arr1's shape
# Reshape arr2 to (2, 1, 2) and then broadcast
arr2_reshaped = arr2[:, np.newaxis, :]  # Shape (2, 1, 2)

# Broadcast arr2_reshaped to match arr1's shape
arr2_broadcasted = np.broadcast_to(arr2_reshaped, (2, 3, 2))  # Shape (2, 3, 2)

# Perform multiplication
# We need to align arr1 with arr2_broadcasted to match dimensions for multiplication
result = arr1[:, :, np.newaxis] * arr2_broadcasted  # Shape (2, 3, 2)

print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Result of multiplication:\n", result)


arr1:
 [[1 2 3]
 [4 5 6]]
arr2:
 [[10 20]
 [30 40]]
Result of multiplication:
 [[[ 10  20]
  [ 20  40]
  [ 30  60]]

 [[120 160]
  [150 200]
  [180 240]]]


Explanation:

    Reshape arr2: arr2 is reshaped to (2, 1, 2) to make it compatible with broadcasting. The np.newaxis adds a new dimension for alignment.
    Broadcast arr2: arr2_reshaped is broadcasted to the shape (2, 3, 2) to match arr1’s shape (2, 3).
    Multiply: Multiply arr1 with the broadcasted arr2.

In [44]:
import numpy as np

# Given 2D NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Calculate the column-wise mean
column_wise_mean = np.mean(arr, axis=0)

print("Original array:\n", arr)
print("Column-wise mean:", column_wise_mean)


Original array:
 [[1 2 3]
 [4 5 6]]
Column-wise mean: [2.5 3.5 4.5]


Explanation:

    np.mean(arr, axis=0): Calculates the mean along the columns (i.e., computes the mean for each column).

In [45]:
import numpy as np

# Given 2D NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find the maximum value in each row
max_values_per_row = np.amax(arr, axis=1)

print("Original array:\n", arr)
print("Maximum values in each row:", max_values_per_row)


Original array:
 [[1 2 3]
 [4 5 6]]
Maximum values in each row: [3 6]


Explanation:

    np.amax(arr, axis=1): Computes the maximum value along the specified axis. Here, axis=1 refers to the row axis, so it finds the maximum value in each row.

In [46]:
import numpy as np

# Given 2D NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find the indices of maximum values in each column
indices_of_max_per_column = np.argmax(arr, axis=0)

print("Original array:\n", arr)
print("Indices of maximum values in each column:", indices_of_max_per_column)


Original array:
 [[1 2 3]
 [4 5 6]]
Indices of maximum values in each column: [1 1 1]


Explanation:

    np.argmax(arr, axis=0): Finds the indices of the maximum values along the specified axis. Here, axis=0 refers to the column axis, so it returns the indices of the maximum values in each column.

In [47]:
import numpy as np

def moving_sum(arr, window_size):
    """
    Calculate the moving sum along rows of a 2D NumPy array.
    
    Parameters:
    arr (np.ndarray): Input 2D array.
    window_size (int): Size of the moving window.
    
    Returns:
    np.ndarray: Array with moving sums along rows.
    """
    # Number of rows and columns in the input array
    num_rows, num_cols = arr.shape
    
    # Initialize the result array
    result = np.zeros((num_rows, num_cols - window_size + 1))
    
    # Calculate the moving sum for each row
    for i in range(num_rows):
        for j in range(num_cols - window_size + 1):
            result[i, j] = np.sum(arr[i, j:j + window_size])
    
    return result

# Given array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Define the window size
window_size = 2

# Calculate the moving sum along rows
moving_sum_result = moving_sum(arr, window_size)

print("Original array:\n", arr)
print("Moving sum with window size", window_size, ":\n", moving_sum_result)


Original array:
 [[1 2 3]
 [4 5 6]]
Moving sum with window size 2 :
 [[ 3.  5.]
 [ 9. 11.]]


Explanation:

    window_size: The number of elements to include in each moving sum window.
    Loop through rows: Iterate over each row of the array.
    Calculate moving sum: For each position in the row, compute the sum of elements within the window size and store it in the result array.

In [48]:
import numpy as np

# Given array
arr = np.array([[2, 4, 6],
                [3, 5, 7]])

# Check if each element is even
is_even = arr % 2 == 0

# Check if all elements in each column are even
all_even_per_column = np.all(is_even, axis=0)

print("Original array:\n", arr)
print("Array of boolean values indicating evenness:\n", is_even)
print("Are all elements in each column even?", all_even_per_column)


Original array:
 [[2 4 6]
 [3 5 7]]
Array of boolean values indicating evenness:
 [[ True  True  True]
 [False False False]]
Are all elements in each column even? [False False False]


Explanation:

    arr % 2 == 0: This creates a boolean array where True indicates the corresponding element is even, and False otherwise.
    np.all(is_even, axis=0): Checks if all elements along each column (axis=0) are True (i.e., all elements in that column are even).

In [49]:
import numpy as np

def reshape_array(arr, m, n):
    """
    Reshape the given NumPy array into a matrix with dimensions (m, n).
    
    Parameters:
    arr (np.ndarray): Input 1D NumPy array.
    m (int): Number of rows in the reshaped matrix.
    n (int): Number of columns in the reshaped matrix.
    
    Returns:
    np.ndarray: Reshaped matrix of shape (m, n).
    """
    # Check if the reshape is possible
    if arr.size != m * n:
        raise ValueError("The total number of elements does not match the dimensions m x n.")
    
    # Reshape the array
    reshaped_matrix = arr.reshape((m, n))
    return reshaped_matrix

# Given array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Define new dimensions
m = 2
n = 3

# Reshape the array
reshaped_matrix = reshape_array(original_array, m, n)

print("Original array:\n", original_array)
print("Reshaped matrix:\n", reshaped_matrix)


Original array:
 [1 2 3 4 5 6]
Reshaped matrix:
 [[1 2 3]
 [4 5 6]]


Explanation:

    arr.reshape((m, n)): Reshapes the array into a matrix with m rows and n columns.
    Error Handling: Ensures the reshape is valid by checking if the total number of elements in the original array matches m * n.

In [ ]:
import numpy as np

def flatten_matrix(matrix):
    """
    Flatten the given 2D NumPy matrix into a 1D array.
    
    Parameters:
    matrix (np.ndarray): Input 2D NumPy array (matrix).
    
    Returns:
    np.ndarray: Flattened 1D array.
    """
    # Flatten the matrix using numpy.flatten()
    flattened_array = matrix.flatten()
    return flattened_array

# Given matrix
input_matrix = np.array([[1, 2, 3],
                         [4, 5, 6]])

# Flatten the matrix
flattened_array = flatten_matrix(input_matrix)

print("Input matrix:\n", input_matrix)
print("Flattened array:\n", flattened_array)


Input matrix:
 [[1 2 3]
 [4 5 6]]
Flattened array:
 [1 2 3 4 5 6]


Explanation:

    matrix.flatten(): Converts the 2D matrix into a 1D array by stacking all elements into a single line.
    numpy.ravel(): Can also be used if you prefer a view of the original data rather than a copy.

In [51]:
import numpy as np

def concatenate_arrays(array1, array2, axis):
    """
    Concatenate two NumPy arrays along a specified axis.
    
    Parameters:
    array1 (np.ndarray): The first array to concatenate.
    array2 (np.ndarray): The second array to concatenate.
    axis (int): The axis along which to concatenate the arrays.
    
    Returns:
    np.ndarray: The concatenated array.
    """
    # Check if the arrays can be concatenated along the specified axis
    if array1.shape[axis] != array2.shape[axis]:
        raise ValueError("The arrays have mismatched shapes along the specified axis.")
    
    # Concatenate the arrays
    concatenated_array = np.concatenate((array1, array2), axis=axis)
    return concatenated_array

# Given arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (rows)
result_axis0 = concatenate_arrays(array1, array2, axis=0)

# Concatenate along axis 1 (columns)
result_axis1 = concatenate_arrays(array1, array2, axis=1)

print("Array1:\n", array1)
print("Array2:\n", array2)
print("Concatenated along axis 0:\n", result_axis0)
print("Concatenated along axis 1:\n", result_axis1)


Array1:
 [[1 2]
 [3 4]]
Array2:
 [[5 6]
 [7 8]]
Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


Explanation:

    np.concatenate((array1, array2), axis=axis): Concatenates the arrays along the specified axis.
    Error Handling: Ensures that the arrays have compatible shapes for the specified axis.

In [52]:
import numpy as np

def split_array(array, num_splits, axis):
    """
    Split a NumPy array into multiple sub-arrays along a specified axis.
    
    Parameters:
    array (np.ndarray): The array to split.
    num_splits (int): Number of splits along the specified axis.
    axis (int): The axis along which to split the array.
    
    Returns:
    list of np.ndarray: List of sub-arrays after splitting.
    """
    # Check if the split is possible
    if array.shape[axis] % num_splits != 0:
        raise ValueError("The array cannot be evenly split along the specified axis.")
    
    # Calculate the size of each split along the specified axis
    indices = np.linspace(0, array.shape[axis], num_splits + 1, dtype=int)
    
    # Split the array
    sub_arrays = np.split(array, indices[1:-1], axis=axis)
    return sub_arrays

# Given array
original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# Number of splits and axis
num_splits = 3
axis = 1

# Split the array
split_result = split_array(original_array, num_splits, axis)

print("Original array:\n", original_array)
print("Split arrays:")
for i, sub_array in enumerate(split_result):
    print(f"Sub-array {i}:\n{sub_array}")


Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Split arrays:
Sub-array 0:
[[1]
 [4]
 [7]]
Sub-array 1:
[[2]
 [5]
 [8]]
Sub-array 2:
[[3]
 [6]
 [9]]




Explanation:

    np.split(array, indices[1:-1], axis=axis): Splits the array along the specified axis at the indices provided. Here, indices are computed to evenly split the array into num_splits parts.
    Error Handling: Ensures that the array can be evenly split along the specified axis.

In [54]:
import numpy as np

def insert_and_delete(array, indices_to_insert, values_to_insert, indices_to_delete):
    """
    Insert and then delete elements from a NumPy array at specified indices.
    
    Parameters:
    array (np.ndarray): The original array.
    indices_to_insert (list of int): Indices at which to insert new values.
    values_to_insert (list of int): Values to insert at the specified indices.
    indices_to_delete (list of int): Indices of elements to delete.
    
    Returns:
    np.ndarray: The modified array after insertion and deletion.
    """
    # Insert elements into the array
    for index, value in zip(indices_to_insert, values_to_insert):
        array = np.insert(array, index, value)
    
    # Delete elements from the array
    # Sort indices in descending order to avoid index shifting issues during deletion
    sorted_indices_to_delete = sorted(indices_to_delete, reverse=True)
    for index in sorted_indices_to_delete:
        array = np.delete(array, index)
    
    return array

# Given array
original_array = np.array([1, 2, 3, 4, 5])

# Indices and values to insert
indices_to_insert = [2, 4]
values_to_insert = [10, 11]

# Indices to delete
indices_to_delete = [1, 3]

# Apply the function
modified_array = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print("Original array:\n", original_array)
print("Modified array:\n", modified_array)


Original array:
 [1 2 3 4 5]
Modified array:
 [ 1 10 11  4  5]


Explanation:

    Insert Elements:
        Iterate over indices_to_insert and values_to_insert to insert each value at the specified index using np.insert.

    Delete Elements:
        Sort indices_to_delete in descending order to handle index shifting during deletion.
        Iterate over the sorted indices and use np.delete to remove elements from the array.

In [55]:
import numpy as np

# Create array arr1 with random integers
arr1 = np.random.randint(1, 100, size=(3, 4))  # Example shape (3x4) with values between 1 and 100

# Create array arr2 with integers from 1 to 10
arr2 = np.arange(1, 11).reshape(2, 5)  # Example shape (2x5) with values from 1 to 10

# Make sure arr1 and arr2 have the same shape for element-wise addition
# For demonstration purposes, reshape arr2 to match the shape of arr1
arr2_resized = np.resize(arr2, arr1.shape)  # Reshape arr2 to the same shape as arr1

# Perform element-wise addition
result = arr1 + arr2_resized

print("Array arr1:\n", arr1)
print("Array arr2 resized to match arr1 shape:\n", arr2_resized)
print("Result of element-wise addition:\n", result)


Array arr1:
 [[54 97  4 97]
 [77 80 24 59]
 [31 66  3 78]]
Array arr2 resized to match arr1 shape:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  1  2]]
Result of element-wise addition:
 [[ 55  99   7 101]
 [ 82  86  31  67]
 [ 40  76   4  80]]


Explanation:

    Create arr1: Generates a 3x4 array with random integers between 1 and 100.
    Create arr2: Generates an array of integers from 1 to 10, reshaped to 2x5.
    Resize arr2: Reshape arr2 to match the shape of arr1 to ensure the arrays are compatible for element-wise addition.
    Element-wise Addition: Adds corresponding elements of arr1 and arr2_resized.

In [56]:
import numpy as np

# Generate arr1 with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1).reshape(2, 5)  # Example shape (2x5)

# Generate arr2 with integers from 1 to 10
arr2 = np.arange(1, 11).reshape(2, 5)  # Example shape (2x5)

# Perform element-wise subtraction
result = arr1 - arr2

print("Array arr1:\n", arr1)
print("Array arr2:\n", arr2)
print("Result of element-wise subtraction:\n", result)


Array arr1:
 [[10  9  8  7  6]
 [ 5  4  3  2  1]]
Array arr2:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Result of element-wise subtraction:
 [[ 9  7  5  3  1]
 [-1 -3 -5 -7 -9]]


Explanation:

    Generate arr1: Use np.arange(10, 0, -1) to create an array with sequential integers from 10 to 1. Reshape it to a 2x5 array.
    Generate arr2: Use np.arange(1, 11) to create an array with integers from 1 to 10. Reshape it to a 2x5 array.
    Element-wise Subtraction: Subtract arr2 from arr1 element-wise.

In [57]:
import numpy as np

# Generate arr1 with random integers
arr1 = np.random.randint(1, 10, size=(2, 5))  # Example shape (2x5) with values between 1 and 10

# Generate arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)  # Shape (5,) with values from 1 to 5

# Reshape arr2 to match the shape of arr1 for element-wise multiplication
arr2_reshaped = arr2.reshape(1, 5)  # Reshape to (1x5) so it can be broadcasted to (2x5)

# Perform element-wise multiplication
result = arr1 * arr2_reshaped

print("Array arr1:\n", arr1)
print("Array arr2 reshaped to match arr1 shape:\n", arr2_reshaped)
print("Result of element-wise multiplication:\n", result)


Array arr1:
 [[2 4 6 1 6]
 [6 4 3 3 9]]
Array arr2 reshaped to match arr1 shape:
 [[1 2 3 4 5]]
Result of element-wise multiplication:
 [[ 2  8 18  4 30]
 [ 6  8  9 12 45]]


Explanation:

    Generate arr1: Use np.random.randint to create an array with random integers. Here, it’s shaped (2, 5).
    Generate arr2: Use np.arange(1, 6) to create an array with integers from 1 to 5. Its shape is (5,).
    Reshape arr2: Reshape arr2 to (1, 5) to enable broadcasting with arr1 during multiplication.
    Element-wise Multiplication: Multiply arr1 and arr2_reshaped element-wise.

In [58]:
import numpy as np

# Generate arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)  # Creates array [2, 4, 6, 8, 10]

# Generate arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)  # Creates array [1, 2, 3, 4, 5]

# Reshape arr1 and arr2 to be compatible for element-wise division
# In this case, both are of the same shape (5,) so no reshaping is needed

# Perform element-wise division
result = arr1 / arr2

print("Array arr1:\n", arr1)
print("Array arr2:\n", arr2)
print("Result of element-wise division:\n", result)


Array arr1:
 [ 2  4  6  8 10]
Array arr2:
 [1 2 3 4 5]
Result of element-wise division:
 [2. 2. 2. 2. 2.]


In [59]:
import numpy as np

# Create arr1 with integers from 1 to 5
arr1 = np.arange(1, 6)  # Creates array [1, 2, 3, 4, 5]

# Create arr2 with the same numbers reversed
arr2 = arr1[::-1]  # Creates array [5, 4, 3, 2, 1]

# Calculate exponentiation of arr1 raised to the power of arr2 element-wise
result = np.power(arr1, arr2)

print("Array arr1:\n", arr1)
print("Array arr2:\n", arr2)
print("Result of element-wise exponentiation:\n", result)


Array arr1:
 [1 2 3 4 5]
Array arr2:
 [5 4 3 2 1]
Result of element-wise exponentiation:
 [ 1 16 27 16  5]


Explanation:

    Generate arr1: Use np.arange(1, 6) to create an array with integers from 1 to 5.
    Generate arr2: Reverse arr1 using slicing [::-1] to create an array with the same numbers in reverse order.
    Element-wise Exponentiation: Use np.power(arr1, arr2) to compute the exponentiation of each element in arr1 raised to the power of the corresponding element in arr2

In [60]:
import numpy as np

def count_substring_occurrences(arr, substring):
    # Convert the NumPy array to a list of strings
    strings = arr.tolist()
    
    # Initialize the count
    count = 0
    
    # Iterate over each string in the array
    for string in strings:
        # Count occurrences of the substring in the current string
        count += string.count(substring)
    
    return count

# Example array and substring
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'

# Count occurrences
result = count_substring_occurrences(arr, substring)

print("Occurrences of substring '{}': {}".format(substring, result))


Occurrences of substring 'hello': 3


Explanation:

    Convert Array to List: Convert the NumPy array to a list of strings to make iteration easier.
    Count Occurrences: Initialize a count variable and iterate over each string in the list. Use the count method of strings to find how many times the substring appears in each string, adding to the total count.
    Return Result: Return the total count of occurrences.

In [61]:
import numpy as np

def extract_uppercase(arr):
    # Initialize an empty list to hold the results
    uppercase_chars = []
    
    # Iterate over each string in the NumPy array
    for string in arr:
        # Extract uppercase characters from the current string
        uppercase_chars.append(''.join(char for char in string if char.isupper()))
    
    # Convert the list back to a NumPy array
    return np.array(uppercase_chars)

# Example array
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

# Extract uppercase characters
result = extract_uppercase(arr)

print("Uppercase characters:\n", result)


Uppercase characters:
 ['H' 'W' 'OAI' 'GPT']


Explanation:

    Initialize List: Create an empty list to store the results.
    Iterate and Extract: For each string in the array, use a generator expression inside join to extract only the uppercase characters.
    Convert to NumPy Array: Convert the list of extracted uppercase characters back to a NumPy array.

In [62]:
import numpy as np

def replace_substring(arr, old_substring, new_substring):
    # Use a list comprehension to replace the substring in each element
    replaced_arr = np.array([string.replace(old_substring, new_substring) for string in arr])
    return replaced_arr

# Example array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Define the substring to replace and the new substring
old_substring = 'apple'
new_substring = 'orange'

# Replace the substring
result = replace_substring(arr, old_substring, new_substring)

print("Array with replaced substrings:\n", result)


Array with replaced substrings:
 ['orange' 'banana' 'grape' 'pineorange']


Explanation:

    List Comprehension: Iterate over each string in the NumPy array and use the replace method to replace occurrences of old_substring with new_substring.
    Convert to NumPy Array: Convert the list of replaced strings back into a NumPy array.

In [63]:
import numpy as np

def concatenate_strings(arr1, arr2):
    # Concatenate strings element-wise
    concatenated_arr = np.char.add(arr1, arr2)
    return concatenated_arr

# Example arrays
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

# Concatenate the strings
result = concatenate_strings(arr1, arr2)

print("Concatenated array:\n", result)


Concatenated array:
 ['HelloOpen' 'WorldAI']


Explanation:

    Use np.char.add: The np.char.add function performs element-wise string concatenation. It is designed for such operations and ensures that the concatenation is applied to each pair of strings from arr1 and arr2.
    Return Result: Return the concatenated NumPy array.

In [64]:
import numpy as np

def longest_string_length(arr):
    # Vectorize the length function
    length_function = np.vectorize(len)
    
    # Get lengths of all strings in the array
    lengths = length_function(arr)
    
    # Find the maximum length
    max_length = np.max(lengths)
    
    return max_length

# Example array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Find the length of the longest string
result = longest_string_length(arr)

print("Length of the longest string:", result)


Length of the longest string: 9


Explanation:

    Vectorize Length Function: Use np.vectorize(len) to create a vectorized version of the len function, allowing it to be applied to each element of the NumPy array.
    Calculate Lengths: Apply this vectorized function to the array to get an array of lengths.
    Find Maximum Length: Use np.max to find the maximum value in the array of lengths.

In [65]:
import numpy as np

# Create a dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, size=100)

# Compute mean
mean = np.mean(dataset)

# Compute median
median = np.median(dataset)

# Compute variance
variance = np.var(dataset)

# Compute standard deviation
std_dev = np.std(dataset)

print("Dataset:\n", dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)


Dataset:
 [ 413  112  417  983  240  684  794  688  893  991  218  702  257   69
  336   62  953  734   64   83  760  535  140  189  149  970 1000  875
  718  989  210  591  234  444  730  427  160  754  487  787  496  931
  628  380  626  132  727  768   31  781  552  208   77  281  942  902
   79  417  636  459  983  729  960  199  639  379  704  474  357  548
   38  866  371  313   10  117  158   84  725  482  428  367   94   92
  290  926  877  236  323  818  961  547  884  687  571  933  977  280
  346  214]
Mean: 508.82
Median: 484.5
Variance: 93959.06759999997
Standard Deviation: 306.5274336825335


In [66]:
import numpy as np

# Generate an array of 50 random numbers between 1 and 100
data = np.random.randint(1, 101, size=50)

# Find the 25th and 75th percentiles
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print("Data:\n", data)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)


Data:
 [ 24  53  18  14   8 100  11  39  29  99  95  26  30  47  12  78  89  65
  32  34  91  27   7  21  43  45  74   2  13  91  63  70  11   6  23  11
  76  98  64  91  70  35   4  98  75  13  77  86  86  58]
25th Percentile: 18.75
75th Percentile: 76.75


Explanation:

    Generate Array: Use np.random.randint(1, 101, size=50) to create an array of 50 random integers between 1 and 100.
    Compute Percentiles: Use np.percentile(data, 25) to compute the 25th percentile and np.percentile(data, 75) for the 75th percentile.

In [67]:
import numpy as np

# Create two arrays representing two sets of variables
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([2, 4, 6, 8, 10])

# Compute the correlation coefficient matrix
correlation_matrix = np.corrcoef(array1, array2)

# Extract the correlation coefficient between array1 and array2
correlation_coefficient = correlation_matrix[0, 1]

print("Correlation Coefficient Matrix:\n", correlation_matrix)
print("Correlation Coefficient between array1 and array2:", correlation_coefficient)


Correlation Coefficient Matrix:
 [[1. 1.]
 [1. 1.]]
Correlation Coefficient between array1 and array2: 0.9999999999999999


Explanation:

    Create Arrays: Define the two arrays for which you want to compute the correlation coefficient.
    Compute Correlation Coefficient Matrix: Use np.corrcoef(array1, array2) to compute the correlation matrix. This matrix contains the correlation coefficients between the variables in the arrays.
    Extract Correlation Coefficient: The correlation coefficient between array1 and array2 is found at position [0, 1] in the correlation matrix.

In [68]:
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8], [9, 10], [11, 12]])

# Perform matrix multiplication using np.dot
result = np.dot(matrix1, matrix2)

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Result of Matrix Multiplication:\n", result)


Matrix 1:
 [[1 2 3]
 [4 5 6]]
Matrix 2:
 [[ 7  8]
 [ 9 10]
 [11 12]]
Result of Matrix Multiplication:
 [[ 58  64]
 [139 154]]


Explanation:

    Create Matrices:
        matrix1 is a 2x3 matrix.
        matrix2 is a 3x2 matrix.
        For matrix multiplication to be valid, the number of columns in matrix1 must be equal to the number of rows in matrix2.

    Perform Matrix Multiplication:
        Use np.dot(matrix1, matrix2) to perform matrix multiplication. The result will be a 2x2 matrix.

In [69]:
import numpy as np

# Create an array of 50 integers between 10 and 1000
data = np.random.randint(10, 1001, size=50)

# Calculate the 10th, 50th (median), and 90th percentiles
percentile_10 = np.percentile(data, 10)
percentile_50 = np.percentile(data, 50)  # Median
percentile_90 = np.percentile(data, 90)

# Calculate the first (25th) and third (75th) quartiles
quartile_1 = np.percentile(data, 25)
quartile_3 = np.percentile(data, 75)

print("Data:\n", data)
print("10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("1st Quartile (25th Percentile):", quartile_1)
print("3rd Quartile (75th Percentile):", quartile_3)


Data:
 [437 760 394 868 520 202  61 902 183 294 935 106 999 675 984 917 665 631
 797 567 533 161 830 773 853 884 975 827  86 979 904 773 232 661 479 252
 257 991 107 242 619 644 591 451 155 672 256 136  95  43]
10th Percentile: 106.9
50th Percentile (Median): 605.0
90th Percentile: 939.0
1st Quartile (25th Percentile): 244.5
3rd Quartile (75th Percentile): 829.25



Explanation:

    Create Array: Use np.random.randint(10, 1001, size=50) to generate an array of 50 random integers between 10 and 1000.
    Calculate Percentiles: Use np.percentile(data, 10), np.percentile(data, 50), and np.percentile(data, 90) to compute the 10th, 50th (median), and 90th percentiles, respectively.
    Calculate Quartiles: Use np.percentile(data, 25) for the 1st quartile (25th percentile) and np.percentile(data, 75) for the 3rd quartile (75th percentile).

In [70]:
import numpy as np

# Create a NumPy array of integers
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Specify the element to find
element_to_find = 50

# Find the index of the specific element
indices = np.where(array == element_to_find)

# Print the index
print("Array:\n", array)
print("Index of element", element_to_find, ":", indices[0])


Array:
 [ 10  20  30  40  50  60  70  80  90 100]
Index of element 50 : [4]


Explanation:

    Create Array: np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100]) creates a NumPy array of integers.
    Find Index: np.where(array == element_to_find) returns a tuple of arrays, where each array contains the indices of elements that satisfy the condition. indices[0] retrieves the index positions from the tuple.

In [71]:
import numpy as np

# Generate a random NumPy array of integers
array = np.random.randint(1, 100, size=10)  # Random integers between 1 and 100, with 10 elements

# Print the original array
print("Original Array:\n", array)

# Sort the array in ascending order
sorted_array = np.sort(array)

# Print the sorted array
print("Sorted Array:\n", sorted_array)


Original Array:
 [20 32 30 57  8 27 93 13 11 28]
Sorted Array:
 [ 8 11 13 20 27 28 30 32 57 93]


In [72]:
import numpy as np

# Given NumPy array
arr = np.array([1, 5, 8, 12, 15])

# Filter elements greater than 20
filtered_elements = arr[arr > 20]

# Print the filtered array
print("Filtered Elements > 20:", filtered_elements)


Filtered Elements > 20: []


Explanation:

    Boolean Indexing: arr > 20 creates a boolean array where each element is True if the corresponding element in arr is greater than 20, and False otherwise.
    Filtering: arr[arr > 20] uses this boolean array to index arr, returning only the elements that satisfy the condition.

In [73]:
import numpy as np

# Given NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Filter elements >= 20 and <= 40
filtered_elements = arr[(arr >= 20) & (arr <= 40)]

# Print the filtered array
print("Filtered Elements (20 ≤ x ≤ 40):", filtered_elements)


Filtered Elements (20 ≤ x ≤ 40): [20 30 40]


Explanation:

    Boolean Indexing with Multiple Conditions:
        (arr >= 20) creates a boolean array where each element is True if it is greater than or equal to 20.
        (arr <= 40) creates a boolean array where each element is True if it is less than or equal to 40.
        The & operator combines these two boolean arrays, resulting in an array where each element is True if it satisfies both conditions.
    Filtering:
        arr[(arr >= 20) & (arr <= 40)] uses this combined boolean array to index arr, returning only the elements that satisfy both conditions.

In [74]:
import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3])

# Check the byte order using the dtype attribute
byteorder = arr.dtype.byteorder

# Interpret the byteorder value
if byteorder == '=':
    print("Byte order: Native (system's default endianness)")
elif byteorder == '<':
    print("Byte order: Little-endian")
elif byteorder == '>':
    print("Byte order: Big-endian")
else:
    print("Byte order: Unknown")


Byte order: Native (system's default endianness)


Explanation:

    Access Byte Order:
        arr.dtype.byteorder returns the byte order of the array.
        '=' indicates that the byte order is native to the system.
        '<' indicates little-endian byte order.
        '>' indicates big-endian byte order.

    Interpret Byte Order:
        The code snippet checks the value of byteorder and prints the appropriate byte order description.

In [75]:
import numpy as np

# Given NumPy array with dtype int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Print the original array and its byte order
print("Original Array:", arr)
print("Original Byte Order:", arr.dtype.byteorder)

# Perform byte swapping in place
arr.byteswap(inplace=True)

# Print the modified array and its byte order
print("Array after Byte Swapping:", arr)
print("Byte Order after Swapping:", arr.dtype.byteorder)


Original Array: [1 2 3]
Original Byte Order: =
Array after Byte Swapping: [16777216 33554432 50331648]
Byte Order after Swapping: =


Explanation:

    Create the Array:
        np.array([1, 2, 3], dtype=np.int32) creates an array of integers with 32-bit integer type.

    Print Original Byte Order:
        arr.dtype.byteorder shows the byte order before swapping.

    Perform Byte Swapping:
        arr.byteswap(inplace=True) swaps the bytes of the array in place, modifying the original array.

    Print Modified Array:
        The array is printed again after byte swapping to show the changes.

In [76]:
import numpy as np

# Given NumPy array with dtype int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Print the original array and its byte order
print("Original Array:", arr)
print("Original Byte Order:", arr.dtype.byteorder)

# Swap byte order without modifying the original array
swapped_arr = arr.newbyteorder()

# Print the swapped array and its byte order
print("Array with Swapped Byte Order:", swapped_arr)
print("Byte Order of Swapped Array:", swapped_arr.dtype.byteorder)


Original Array: [1 2 3]
Original Byte Order: =
Array with Swapped Byte Order: [16777216 33554432 50331648]
Byte Order of Swapped Array: >


Explanation:

    Create the Array:
        np.array([1, 2, 3], dtype=np.int32) creates an array of integers with 32-bit integer type.

    Print Original Byte Order:
        arr.dtype.byteorder shows the byte order of the original array.

    Swap Byte Order:
        arr.newbyteorder() creates a new array with the byte order swapped. This does not modify the original array but returns a new array with swapped byte order.

    Print New Array:
        The new array swapped_arr is printed to show the effect of the byte order swap.

Explanation of Output:

    Original Array: [1 2 3] (integer values in native byte order).
    Original Byte Order: Native endianness (e.g., little-endian).
    Array with Swapped Byte Order: Shows the values after swapping bytes. The byte order is different, so the values appear changed.
    Byte Order of Swapped Array: < indicates little-endian, but it will match the swapped byte order, which can be either < or > depending on the original system's endianness.

This approach allows you to inspect or use byte-swapped data without altering the original data structure.

In [77]:
import numpy as np
import sys

# Given NumPy array with dtype int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Check the system's endianness
system_byteorder = sys.byteorder

# Print the original array and its byte order
print("Original Array:", arr)
print("Original Byte Order:", arr.dtype.byteorder)
print("System Byte Order:", system_byteorder)

# Conditionally swap byte order
if system_byteorder == 'little':
    swapped_arr = arr.newbyteorder('>')
elif system_byteorder == 'big':
    swapped_arr = arr.newbyteorder('<')
else:
    swapped_arr = arr  # Default to no change if unknown

# Print the swapped array and its byte order
print("Array with Conditional Byte Order Swapping:", swapped_arr)
print("Byte Order of Swapped Array:", swapped_arr.dtype.byteorder)


Original Array: [1 2 3]
Original Byte Order: =
System Byte Order: little
Array with Conditional Byte Order Swapping: [16777216 33554432 50331648]
Byte Order of Swapped Array: >


Explanation:

    Create the Array:
        np.array([1, 2, 3], dtype=np.int32) creates a 32-bit integer array.

    Check System Byte Order:
        sys.byteorder provides the system's byte order ('little' or 'big').

    Swap Byte Order Conditionally:
        If the system's byte order is little-endian, arr.newbyteorder('>') is used to convert to big-endian.
        If the system's byte order is big-endian, arr.newbyteorder('<') is used to convert to little-endian.
        If the system byte order is unknown, the array remains unchanged.

    Print Results:
        The original and swapped arrays, along with their byte orders, are printed.

In [ ]:
import numpy as np
import sys

# Given NumPy array with dtype int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Check the system's endianness
system_byteorder = sys.byteorder

# Get the byte order of the array
array_byteorder = arr.dtype.byteorder

# Print the system's and array's byte order
print("System Byte Order:", system_byteorder)
print("Array Byte Order:", array_byteorder)

# Determine if byte swapping is necessary
if array_byteorder == '=':
    # Array uses the system's native byte order
    print("No byte swapping needed (native byte order).")
elif (system_byteorder == 'little' and array_byteorder == '>') or (system_byteorder == 'big' and array_byteorder == '<'):
    # System's byte order and array's byte order differ
    print("Byte swapping needed.")
else:
    # Handle unknown or other cases
    print("Byte swapping might be needed, but the situation is unclear.")


Explanation:

    Create the Array:
        np.array([1, 2, 3], dtype=np.int32) creates an array of 32-bit integers.

    Check System Byte Order:
        sys.byteorder provides the system's endianness ('little' or 'big').

    Get Array Byte Order:
        arr.dtype.byteorder provides the byte order of the array ('<', '>', or '=' for native).

    Determine Byte Swapping Necessity:
        If array_byteorder is '=', the array uses the system's native byte order, so no byte swapping is needed.
        If array_byteorder is different from the system's byte order, byte swapping is needed. For instance, if the system is little-endian ('little') and the array is big-endian ('>'), or vice versa.
        The last condition handles cases where the situation might be unclear.

In [78]:
import numpy as np

# Create a NumPy array with values from 1 to 10
arr1 = np.arange(1, 11)
print("Original array (arr1):", arr1)

# Create a copy of arr1
copy_arr = arr1.copy()
print("Copied array (copy_arr):", copy_arr)

# Modify an element in copy_arr
copy_arr[0] = 99
print("Modified copied array (copy_arr):", copy_arr)

# Check if modifying copy_arr affects arr1
print("Original array after modification (arr1):", arr1)


Original array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Copied array (copy_arr): [ 1  2  3  4  5  6  7  8  9 10]
Modified copied array (copy_arr): [99  2  3  4  5  6  7  8  9 10]
Original array after modification (arr1): [ 1  2  3  4  5  6  7  8  9 10]




Explanation:

    np.arange(1, 11) creates an array with values from 1 to 10.
    arr1.copy() creates a copy of arr1. This ensures that copy_arr is an independent array and modifications to it will not affect arr1.
    Modifying copy_arr does not affect arr1, as demonstrated by the printed results.

When you run this code, you should see that arr1 remains unchanged even after modifying copy_arr.

In [79]:
import numpy as np

# Create a 2D NumPy array with random integers between 0 and 9, of shape (3, 3)
matrix = np.random.randint(0, 10, size=(3, 3))
print("Original matrix:\n", matrix)

# Extract a slice from the matrix
view_slice = matrix[1:, 1:]  # This is a slice of the original matrix
print("View slice:\n", view_slice)

# Modify an element in the view_slice
view_slice[0, 0] = 99
print("Modified view slice:\n", view_slice)

# Check if modifying view_slice affects the original matrix
print("Original matrix after modification:\n", matrix)


Original matrix:
 [[9 5 8]
 [5 6 2]
 [6 8 3]]
View slice:
 [[6 2]
 [8 3]]
Modified view slice:
 [[99  2]
 [ 8  3]]
Original matrix after modification:
 [[ 9  5  8]
 [ 5 99  2]
 [ 6  8  3]]


Explanation:

    np.random.randint(0, 10, size=(3, 3)) creates a 3x3 array with random integers between 0 and 9.
    matrix[1:, 1:] extracts a slice starting from the element at index (1,1) to the end. This slice is a view of the original matrix.
    Modifying an element in view_slice will affect the original matrix because slices are views of the original array.

In [80]:
import numpy as np

# Create a NumPy array with sequential integers from 1 to 12, shape (4, 3)
array_a = np.arange(1, 13).reshape(4, 3)
print("Original array (array_a):\n", array_a)

# Extract a slice from array_a
view_b = array_a[1:, 1:]  # Slice from (1,1) to the end
print("View slice (view_b):\n", view_b)

# Broadcast the addition of 5 to view_b
view_b += 5
print("Modified view slice (view_b) after addition:\n", view_b)

# Check if modifying view_b affects the original array_a
print("Original array (array_a) after modification:\n", array_a)


Original array (array_a):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
View slice (view_b):
 [[ 5  6]
 [ 8  9]
 [11 12]]
Modified view slice (view_b) after addition:
 [[10 11]
 [13 14]
 [16 17]]
Original array (array_a) after modification:
 [[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 16 17]]


Explanation:

    np.arange(1, 13).reshape(4, 3) creates a 4x3 array with sequential integers from 1 to 12.
    array_a[1:, 1:] extracts a slice starting from index (1,1) to the end, which is a view of the original array.
    view_b += 5 broadcasts the addition of 5 to each element of the slice view_b.

In [81]:
import numpy as np

# Create a NumPy array with values from 1 to 8, shape (2, 4)
orig_array = np.arange(1, 9).reshape(2, 4)
print("Original array (orig_array):\n", orig_array)

# Create a reshaped view of shape (4, 2)
reshaped_view = orig_array.reshape(4, 2)
print("Reshaped view (reshaped_view):\n", reshaped_view)

# Modify an element in reshaped_view
reshaped_view[0, 0] = 99
print("Modified reshaped view (reshaped_view):\n", reshaped_view)

# Check if modifying reshaped_view affects the original orig_array
print("Original array (orig_array) after modification:\n", orig_array)


Original array (orig_array):
 [[1 2 3 4]
 [5 6 7 8]]
Reshaped view (reshaped_view):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Modified reshaped view (reshaped_view):
 [[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]
Original array (orig_array) after modification:
 [[99  2  3  4]
 [ 5  6  7  8]]


Explanation:

    np.arange(1, 9).reshape(2, 4) creates a 2x4 array with values from 1 to 8.
    orig_array.reshape(4, 2) creates a reshaped view of orig_array with shape (4, 2). This view is not a copy but a different way to view the same data.
    Modifying an element in reshaped_view will also affect the original orig_array because reshaped_view is just a different view of orig_array

In [82]:
import numpy as np

# Create a NumPy array with random integers between 1 and 10, shape (3, 4)
data = np.random.randint(1, 10, size=(3, 4))
print("Original array (data):\n", data)

# Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()
print("Data copy (elements greater than 5):\n", data_copy)

# Modify an element in data_copy
data_copy[0] = 99
print("Modified data copy:\n", data_copy)

# Check if modifying data_copy affects the original data
print("Original array (data) after modification:\n", data)


Original array (data):
 [[5 1 3 8]
 [8 5 3 4]
 [1 4 4 1]]
Data copy (elements greater than 5):
 [8 8]
Modified data copy:
 [99  8]
Original array (data) after modification:
 [[5 1 3 8]
 [8 5 3 4]
 [1 4 4 1]]


Explanation:

    np.random.randint(1, 10, size=(3, 4)) creates a 3x4 array with random integers between 1 and 9.
    data[data > 5].copy() creates a copy of elements from data that are greater than 5. Using .copy() ensures that data_copy is an independent array.
    Modifying an element in data_copy will not affect the original data since data_copy is a separate copy created using .copy().

In [83]:
import numpy as np

# Create two matrices A and B of identical shape with random integers
A = np.random.randint(1, 10, size=(3, 3))
B = np.random.randint(1, 10, size=(3, 3))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# Perform addition between A and B
addition_result = A + B
print("Addition of A and B:\n", addition_result)

# Perform subtraction between A and B
subtraction_result = A - B
print("Subtraction of A and B:\n", subtraction_result)


Matrix A:
 [[9 2 6]
 [2 6 5]
 [3 2 9]]
Matrix B:
 [[9 5 1]
 [8 5 7]
 [6 7 5]]
Addition of A and B:
 [[18  7  7]
 [10 11 12]
 [ 9  9 14]]
Subtraction of A and B:
 [[ 0 -3  5]
 [-6  1 -2]
 [-3 -5  4]]


Explanation:

    np.random.randint(1, 10, size=(3, 3)) generates random integers between 1 and 9 and creates two matrices A and B of shape (3, 3).
    A + B performs element-wise addition of matrices A and B.
    A - B performs element-wise subtraction of B from A.

In [84]:
import numpy as np

# Generate two matrices
C = np.random.randint(1, 10, size=(3, 2))
D = np.random.randint(1, 10, size=(2, 4))

print("Matrix C (3x2):\n", C)
print("Matrix D (2x4):\n", D)

# Perform matrix multiplication
result = np.matmul(C, D)
# Alternatively, you can use the @ operator: result = C @ D

print("Result of C multiplied by D:\n", result)


Matrix C (3x2):
 [[7 1]
 [2 3]
 [5 3]]
Matrix D (2x4):
 [[8 8 2 5]
 [6 5 5 5]]
Result of C multiplied by D:
 [[62 61 19 40]
 [34 31 19 25]
 [58 55 25 40]]


Explanation:

    np.random.randint(1, 10, size=(3, 2)) creates a 3x2 matrix C with random integers between 1 and 9.
    np.random.randint(1, 10, size=(2, 4)) creates a 2x4 matrix D with random integers between 1 and 9.
    np.matmul(C, D) performs matrix multiplication. You could also use C @ D for the same result.

In [85]:
import numpy as np

# Create a matrix E (let's use a 3x3 matrix for example)
E = np.random.randint(1, 10, size=(3, 3))
print("Matrix E:\n", E)

# Find the transpose of matrix E
E_transpose = E.T
print("Transpose of matrix E:\n", E_transpose)


Matrix E:
 [[5 3 9]
 [2 8 5]
 [4 8 2]]
Transpose of matrix E:
 [[5 2 4]
 [3 8 8]
 [9 5 2]]


Explanation:

    np.random.randint(1, 10, size=(3, 3)) generates a 3x3 matrix E with random integers between 1 and 9.
    E.T computes the transpose of matrix E, swapping rows with columns.

In [86]:
import numpy as np

# Generate a square matrix F (let's use a 3x3 matrix for this example)
F = np.random.randint(1, 10, size=(3, 3))
print("Matrix F:\n", F)

# Compute the determinant of matrix F
determinant_F = np.linalg.det(F)
print("Determinant of matrix F:", determinant_F)


Matrix F:
 [[9 3 7]
 [9 5 7]
 [4 3 2]]
Determinant of matrix F: -19.999999999999996


Explanation:

    np.random.randint(1, 10, size=(3, 3)) creates a 3x3 square matrix F with random integers between 1 and 9.
    np.linalg.det(F) computes the determinant of matrix F.

In [87]:
import numpy as np

# Generate a square matrix G (let's use a 3x3 matrix for this example)
G = np.random.randint(1, 10, size=(3, 3))
print("Matrix G:\n", G)

# Compute the determinant to check if the matrix is invertible
determinant_G = np.linalg.det(G)
print("Determinant of matrix G:", determinant_G)

# Compute the inverse of matrix G if it is invertible
if determinant_G != 0:
    G_inverse = np.linalg.inv(G)
    print("Inverse of matrix G:\n", G_inverse)
else:
    print("Matrix G is singular and does not have an inverse.")


Matrix G:
 [[2 3 2]
 [3 1 1]
 [9 3 7]]
Determinant of matrix G: -28.00000000000001
Inverse of matrix G:
 [[-0.14285714  0.53571429 -0.03571429]
 [ 0.42857143  0.14285714 -0.14285714]
 [-0.         -0.75        0.25      ]]


Explanation:

    np.random.randint(1, 10, size=(3, 3)) creates a 3x3 square matrix G with random integers between 1 and 9.
    np.linalg.det(G) calculates the determinant of G. If the determinant is zero, the matrix is singular and does not have an inverse.
    np.linalg.inv(G) computes the inverse of G if it is invertible.